# Generated by Django 6.0 on 2025-12-14 01:43

import chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fillow', '0013_alter_instance_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Chatbot')),
                ('active', models.BooleanField(default=True, verbose_name='Ativado/Desativado')),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('gemini', 'Google (Gemini)')], default='openai', max_length=20, verbose_name='Provedor de IA')),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='Modelo (Ex: gpt-4, gemini-pro)')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key (Cole aqui)')),
                ('context', models.TextField(blank=True, help_text='Quem é o bot? Como ele deve agir? O que ele sabe sobre a empresa?', verbose_name='Contexto do Sistema')),
                ('skills', models.TextField(blank=True, help_text='Lista de coisas que ele deve fazer. Ex: Agendar, responder preços, transferir.', verbose_name='Habilidades/Instruções')),
                ('token_usage_type', models.CharField(choices=[('unlimited', 'Ilimitado'), ('limited', 'Limitado (Definir Valor)')], default='unlimited', max_length=15, verbose_name='Tipo de Limite')),
                ('token_limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Limite de Tokens (Se limitado)')),
                ('current_tokens_used', models.PositiveIntegerField(default=0, editable=False, verbose_name='Tokens Usados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_config', to='fillow.instance', verbose_name='Instância Conectada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Conexão Chatbot',
                'verbose_name_plural': 'Conexões Chatbot',
            },
        ),
        migrations.CreateModel(
            name='ChatbotMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chatbot.models.chatbot_media_path, verbose_name='Arquivo')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Arquivo/Documento'), ('sticker', 'Figurinha')], default='document', max_length=20)),
                ('is_accessible_by_ai', models.BooleanField(default=True, help_text='Se marcado, a IA poderá decidir enviar este arquivo.', verbose_name='Acessível pela IA?')),
                ('description', models.TextField(help_text="Explique para a IA o que é este arquivo para que ela saiba quando enviar. Ex: 'Tabela de preços PDF', 'Foto do produto X'.", verbose_name='Descrição/Palavras-chave')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='chatbot.chatbot')),
            ],
            options={
                'verbose_name': 'Mídia do Chatbot',
                'verbose_name_plural': 'Mídias do Chatbot',
            },
        ),
    ]
