# Generated by Django 6.0 on 2025-12-14 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='allow_audio_response',
            field=models.BooleanField(default=True, verbose_name='Pode enviar Áudio?'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='allow_media_response',
            field=models.BooleanField(default=True, verbose_name='Pode enviar Mídia (Img/Doc)?'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='simulate_typing',
            field=models.BooleanField(default=True, verbose_name='Simular Digitação?'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='trigger_on_groups',
            field=models.BooleanField(default=False, verbose_name='Responder em Grupos?'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='trigger_on_unknown',
            field=models.BooleanField(default=True, verbose_name='Responder Números Desconhecidos?'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='typing_time',
            field=models.PositiveIntegerField(default=3000, help_text='Tempo simulando digitação antes de enviar.', verbose_name='Tempo de Digitação (ms)'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='context',
            field=models.TextField(blank=True, verbose_name='Contexto do Sistema'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='model_name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Habilidades/Instruções'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Limite de Tokens'),
        ),
        migrations.AlterField(
            model_name='chatbotmedia',
            name='description',
            field=models.TextField(verbose_name='Descrição/Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='chatbotmedia',
            name='is_accessible_by_ai',
            field=models.BooleanField(default=True, verbose_name='Acessível pela IA?'),
        ),
        migrations.CreateModel(
            name='ChatbotContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_jid', models.CharField(max_length=50, verbose_name='Número (JID)')),
                ('push_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome no WhatsApp')),
                ('first_interaction', models.DateTimeField(auto_now_add=True, verbose_name='Primeira Interação')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Última Interação')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloqueado pelo Bot?')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações Internas')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='chatbot.chatbot')),
            ],
            options={
                'verbose_name': 'Contato do Chatbot',
                'verbose_name_plural': 'Contatos do Chatbot',
                'unique_together': {('chatbot', 'remote_jid')},
            },
        ),
    ]
