# Generated by Django 6.0 on 2025-12-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbot_allow_audio_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='typing_time',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='typing_time_max',
            field=models.PositiveIntegerField(default=5000, help_text='Máximo de tempo simulando digitação.', verbose_name='Tempo Max Digitação (ms)'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='typing_time_min',
            field=models.PositiveIntegerField(default=2000, help_text='Mínimo de tempo simulando digitação.', verbose_name='Tempo Min Digitação (ms)'),
        ),
    ]
