# Generated by Django 6.0 on 2025-12-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatbot_typing_time_chatbot_typing_time_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='typing_time_max',
            field=models.PositiveIntegerField(default=5000, help_text='Máximo de tempo simulando digitação.', verbose_name='Tempo Max (ms)'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='typing_time_min',
            field=models.PositiveIntegerField(default=2000, help_text='Mínimo de tempo simulando digitação.', verbose_name='Tempo Min (ms)'),
        ),
    ]
