# Generated by Django 6.0 on 2025-12-15 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_chatbot_typing_time_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='context',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='current_tokens_used',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='token_limit',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='token_usage_type',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='business_hours',
            field=models.TextField(default=1, help_text='Ex: Seg-Sex das 09h às 18h.', verbose_name='Horário de Atendimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='company_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome da Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='company_summary',
            field=models.TextField(default=1, help_text='O que a empresa faz, produtos, missão, etc.', verbose_name='Resumo da Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='company_website',
            field=models.URLField(blank=True, null=True, verbose_name='Site da Empresa'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='conversation_tone',
            field=models.CharField(choices=[('formal', 'Formal e Respeitoso'), ('casual', 'Casual e Descontraído'), ('friendly', 'Amigável e Empático'), ('enthusiastic', 'Entusiasta e Energético'), ('professional', 'Profissional e Direto')], default='friendly', max_length=50, verbose_name='Tom da Conversa'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='conversations_count',
            field=models.IntegerField(default=0, verbose_name='Conversas no Mês Atual'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='extra_instructions',
            field=models.TextField(blank=True, verbose_name='Instruções Extras (Prompt Manual)'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='last_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='sector',
            field=models.CharField(default=1, help_text='Ex: Moda, Odontologia', max_length=100, verbose_name='Setor de Atuação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatbot',
            name='segment',
            field=models.CharField(choices=[('retail', 'Varejo / Loja'), ('tech', 'Tecnologia / Software'), ('health', 'Saúde / Clínica'), ('food', 'Alimentação / Restaurante'), ('real_estate', 'Imobiliária'), ('education', 'Educação / Cursos'), ('services', 'Prestação de Serviços'), ('other', 'Outro')], default='other', max_length=50, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_1_active',
            field=models.BooleanField(default=False, verbose_name='Ativar Transf. 1'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_1_label',
            field=models.CharField(blank=True, choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas / Comercial'), ('financial', 'Financeiro'), ('attendance', 'Atendimento Geral'), ('scheduling', 'Agendamento'), ('other', 'Outro')], max_length=50, null=True, verbose_name='Setor 1'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_1_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp 1'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_2_active',
            field=models.BooleanField(default=False, verbose_name='Ativar Transf. 2'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_2_label',
            field=models.CharField(blank=True, choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas / Comercial'), ('financial', 'Financeiro'), ('attendance', 'Atendimento Geral'), ('scheduling', 'Agendamento'), ('other', 'Outro')], max_length=50, null=True, verbose_name='Setor 2'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_2_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp 2'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_3_active',
            field=models.BooleanField(default=False, verbose_name='Ativar Transf. 3'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_3_label',
            field=models.CharField(blank=True, choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas / Comercial'), ('financial', 'Financeiro'), ('attendance', 'Atendimento Geral'), ('scheduling', 'Agendamento'), ('other', 'Outro')], max_length=50, null=True, verbose_name='Setor 3'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_3_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp 3'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_4_active',
            field=models.BooleanField(default=False, verbose_name='Ativar Transf. 4'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_4_label',
            field=models.CharField(blank=True, choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas / Comercial'), ('financial', 'Financeiro'), ('attendance', 'Atendimento Geral'), ('scheduling', 'Agendamento'), ('other', 'Outro')], max_length=50, null=True, verbose_name='Setor 4'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_4_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp 4'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_5_active',
            field=models.BooleanField(default=False, verbose_name='Ativar Transf. 5'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_5_label',
            field=models.CharField(blank=True, choices=[('support', 'Suporte Técnico'), ('sales', 'Vendas / Comercial'), ('financial', 'Financeiro'), ('attendance', 'Atendimento Geral'), ('scheduling', 'Agendamento'), ('other', 'Outro')], max_length=50, null=True, verbose_name='Setor 5'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='transf_5_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp 5'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Bot Ativo?'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('gemini', 'Google (Gemini)')], default='gemini', max_length=20, verbose_name='Provedor de IA'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='allow_media_response',
            field=models.BooleanField(default=True, verbose_name='Pode enviar Mídia?'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='model_name',
            field=models.CharField(default='gemini-pro', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome Interno do Bot'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='typing_time_max',
            field=models.PositiveIntegerField(default=5000, verbose_name='Tempo Max (ms)'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='typing_time_min',
            field=models.PositiveIntegerField(default=2000, verbose_name='Tempo Min (ms)'),
        ),
    ]
