# Generated by Django 6.0 on 2025-12-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_chatbot_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='context',
            field=models.TextField(blank=True, null=True, verbose_name='Contexto do Sistema (Prompt Inicial)'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='current_tokens_used',
            field=models.IntegerField(default=0, verbose_name='Total de Tokens Consumidos'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades & Instruções'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='token_limit',
            field=models.IntegerField(default=0, help_text='Defina 0 para ilimitado, caso o tipo permita.', verbose_name='Limite Máximo de Tokens'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='token_usage_type',
            field=models.CharField(choices=[('daily', 'Diário'), ('monthly', 'Mensal'), ('lifetime', 'Total Vitalício'), ('infinity', 'Sem Limites')], default='infinity', max_length=20, verbose_name='Tipo de Limite'),
        ),
    ]
