# Generated by Django 6.0 on 2025-12-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_chatbot_context_chatbot_current_tokens_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='history_limit',
            field=models.IntegerField(default=10, help_text='Quantas mensagens passadas o bot deve analisar?', verbose_name='Qtd. Mensagens de Memória'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='use_history',
            field=models.BooleanField(default=True, help_text='Se ativo, o bot lerá as últimas mensagens para manter o contexto.', verbose_name='Lembrar Conversa Anterior?'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token_limit',
            field=models.IntegerField(default=0, help_text='Defina 0 para ilimitado.', verbose_name='Limite Máximo de Tokens'),
        ),
    ]
