# Generated by Django 6.0 on 2025-12-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatbot_history_limit_chatbot_use_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='history_limit',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='use_history',
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token_limit',
            field=models.IntegerField(default=0, help_text='Defina 0 para ilimitado, caso o tipo permita.', verbose_name='Limite Máximo de Tokens'),
        ),
    ]
