# Generated by Django 6.0 on 2025-12-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_chatbot_history_limit_chatbot_use_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmedia',
            name='send_rules',
            field=models.TextField(blank=True, help_text="Explique para a IA em qual momento este arquivo deve ser enviado. Ex: 'Quando o cliente pedir o cardápio'.", null=True, verbose_name='Regras de Envio (Quando enviar?)'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token_limit',
            field=models.IntegerField(default=0, help_text='Defina 0 para ilimitado, caso o tipo permita.', verbose_name='Limite Máximo de Tokens'),
        ),
    ]
