# Generated by Django 6.0 on 2025-12-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_chatbotmedia_send_rules_alter_chatbot_token_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='conversations_count',
            field=models.IntegerField(default=0, verbose_name='Conversas no Período'),
        ),
    ]
