# Generated by Django 6.0 on 2025-12-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_chatbot_conversations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='conversations_count',
            field=models.IntegerField(default=0, verbose_name='Conversas no Mês Atual'),
        ),
    ]
