# Generated by Django 6.0 on 2025-12-16 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_alter_chatbot_conversations_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço')),
                ('max_chatbots', models.PositiveIntegerField(default=1, help_text='Quantos bots o cliente pode criar.', verbose_name='Máx. Chatbots')),
                ('max_conversations', models.PositiveIntegerField(default=1000, help_text='Limite de conversas dentro do período escolhido.', verbose_name='Máx. Conversas')),
                ('periodicity', models.CharField(choices=[('infinity', 'Sem Limites (Infinito)'), ('daily', 'Diário'), ('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='Renovação do Limite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano de Chatbot',
                'verbose_name_plural': 'Planos de Chatbot',
            },
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='conversations_count',
            field=models.IntegerField(default=0, verbose_name='Conversas no Período Atual'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token_usage_type',
            field=models.CharField(choices=[('daily', 'Diário'), ('monthly', 'Mensal'), ('lifetime', 'Total Vitalício'), ('infinity', 'Sem Limites')], default='infinity', max_length=20, verbose_name='Tipo de Limite (Token)'),
        ),
        migrations.AlterField(
            model_name='chatbotmedia',
            name='send_rules',
            field=models.TextField(blank=True, help_text='Explique para a IA quando enviar este arquivo.', null=True, verbose_name='Regras de Envio (Quando enviar?)'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Assinatura Ativa?')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotplan', verbose_name='Plano Atual')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_subscription', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura do Usuário',
                'verbose_name_plural': 'Assinaturas dos Usuários',
            },
        ),
    ]
