# Generated by Django 6.0 on 2025-12-17 23:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do Bot')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('flow_json', models.JSONField(blank=True, default=dict, verbose_name='Fluxo (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowbots', to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'FlowBot',
                'verbose_name_plural': 'FlowBots',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FlowConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('visitor_name', models.CharField(blank=True, default='', max_length=120)),
                ('visitor_whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='flowbot.flowbot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Conversa do FlowBot',
                'verbose_name_plural': 'Conversas do FlowBot',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='FlowMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='flowbot_media/%Y/%m/', verbose_name='Arquivo')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('file', 'Arquivo'), ('video', 'Vídeo')], default='file', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=140, verbose_name='Título')),
                ('caption', models.TextField(blank=True, default='', verbose_name='Legenda/Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='flowbot.flowbot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Mídia do FlowBot',
                'verbose_name_plural': 'Mídias do FlowBot',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FlowMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_visitor', models.BooleanField(default=False, verbose_name='Veio do visitante?')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('media', 'Mídia'), ('system', 'Sistema')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='flowbot.flowconversation', verbose_name='Conversa')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='flowbot.flowmedia')),
            ],
            options={
                'verbose_name': 'Mensagem do FlowBot',
                'verbose_name_plural': 'Mensagens do FlowBot',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
