# Generated by Django 6.0 on 2025-12-17 10:55

import django.db.models.deletion
import uuid
import wpbot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Bot')),
                ('api_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Chave de API (Secret)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('company_name', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('company_summary', models.TextField(verbose_name='Resumo da Empresa')),
                ('business_hours', models.TextField(blank=True, verbose_name='Horário de Atendimento')),
                ('conversation_tone', models.CharField(choices=[('formal', 'Formal e Respeitoso'), ('casual', 'Casual e Descontraído'), ('friendly', 'Amigável e Empático'), ('enthusiastic', 'Entusiasta e Energético'), ('professional', 'Profissional e Direto')], default='friendly', max_length=50)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('gemini', 'Google (Gemini)')], default='gemini', max_length=20)),
                ('model_name', models.CharField(default='gemini-pro', max_length=50, verbose_name='Modelo IA')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key da IA')),
                ('context', models.TextField(blank=True, verbose_name='Contexto (Prompt Sistema)')),
                ('skills', models.TextField(blank=True, verbose_name='Habilidades')),
                ('use_history', models.BooleanField(default=True, verbose_name='Usar Memória?')),
                ('history_limit', models.IntegerField(default=10, verbose_name='Limite de Mensagens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordpress_bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordpressContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.CharField(max_length=100, verbose_name='ID da Sessão/Cookie')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp/Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('input_state', models.IntegerField(default=1, verbose_name='Estado de Entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='wpbot.wordpressbot')),
            ],
            options={
                'unique_together': {('bot', 'session_uuid')},
            },
        ),
        migrations.CreateModel(
            name='WordpressMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=wpbot.models.wp_media_path)),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Arquivo/PDF')], default='document', max_length=20)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('send_rules', models.TextField(blank=True, verbose_name='Quando enviar?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='wpbot.wordpressbot')),
            ],
        ),
        migrations.CreateModel(
            name='WordpressMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Usuário/Visitante'), ('bot', 'Bot/IA')], max_length=10)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wpbot.wordpresscontact')),
            ],
        ),
    ]
