# Generated by Django 6.0 on 2025-12-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressApiErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(default='/api/chat/', max_length=255)),
                ('request_data', models.TextField(verbose_name='Dados Recebidos')),
                ('error_message', models.TextField(verbose_name='Mensagem de Erro')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Stack Trace')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wpbot.wordpressbot')),
            ],
        ),
    ]
