# Generated by Django 6.0 on 2026-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wpbot', '0002_wordpressapierrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpressbot',
            name='django_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wordpressbot',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wordpressbot',
            name='last_sync_site',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wordpressbot',
            name='prefer_server_settings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wordpressbot',
            name='wp_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='wordpressmessage',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
