# Generated by Django 4.2 on 2024-11-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacaoatendimentomenor',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='autorizacaoimagem',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='contratocolaboradores',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='declaracaoetniaraca',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='fichaadmissaoclt',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='fichaservico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='fichaservico',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='formulariocontratacao',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='recibopagamentoautonomo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Atendimento',
        ),
        migrations.DeleteModel(
            name='AutorizacaoAtendimentoMenor',
        ),
        migrations.DeleteModel(
            name='AutorizacaoImagem',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ContratoColaboradores',
        ),
        migrations.DeleteModel(
            name='DeclaracaoEtniaRaca',
        ),
        migrations.DeleteModel(
            name='FichaAdmissaoCLT',
        ),
        migrations.DeleteModel(
            name='FichaServico',
        ),
        migrations.DeleteModel(
            name='FormularioContratacao',
        ),
        migrations.DeleteModel(
            name='ReciboPagamentoAutonomo',
        ),
    ]
