# Generated by Django 4.2 on 2024-11-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0002_remove_autorizacaoatendimentomenor_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=12, unique=True)),
                ('orgao', models.CharField(max_length=50)),
                ('profissao', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('menor_idade', models.BooleanField()),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=10)),
                ('numero_filhos', models.IntegerField(default=0)),
                ('meninas', models.IntegerField(default=0)),
                ('meninos', models.IntegerField(default=0)),
                ('numero_filhos_deficiencia', models.IntegerField(default=0)),
                ('diagnostico_deficiencia', models.TextField(blank=True, null=True)),
                ('atendimento_especializado', models.BooleanField()),
                ('escolaridade', models.CharField(choices=[('Ensino Fundamental I - 1º ao 5º ano', 'Ensino Fundamental I - 1º ao 5º ano'), ('Ensino Fundamental II - 6º ao 9º ano', 'Ensino Fundamental II - 6º ao 9º ano'), ('Ensino Médio', 'Ensino Médio'), ('Nível Superior Completo', 'Nível Superior Completo'), ('Nível Superior Incompleto', 'Nível Superior Incompleto'), ('Pós Graduação', 'Pós Graduação')], max_length=50)),
                ('religiao', models.CharField(max_length=50)),
                ('residencia', models.CharField(choices=[('Propria', 'Própria'), ('Alugada', 'Alugada'), ('Emprestada', 'Emprestada')], max_length=20)),
                ('trabalha', models.BooleanField()),
                ('situacao_trabalhista', models.CharField(blank=True, choices=[('MEI', 'MEI'), ('Seguro Desemprego/ Pensão', 'Seguro Desemprego/ Pensão'), ('Trabalho Formal com Carteira', 'Trabalho Formal com Carteira'), ('Trabalho Informal/ Extra', 'Trabalho Informal/ Extra'), ('Aposentada(o)', 'Aposentada(o)'), ('Servidor Público', 'Servidor Público')], max_length=50, null=True)),
                ('renda_pessoal', models.CharField(choices=[('Salário Mínimo', 'Salário Mínimo'), ('Maior que salário mínimo', 'Maior que salário mínimo'), ('Menor que salário mínimo', 'Menor que salário mínimo')], max_length=50)),
                ('renda_familiar', models.CharField(choices=[('Salário Mínimo', 'Salário Mínimo'), ('Maior que salário mínimo', 'Maior que salário mínimo'), ('Menor que salário mínimo', 'Menor que salário mínimo')], max_length=50)),
                ('queixa_principal', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_profissional', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('profissao', models.CharField(max_length=100)),
                ('registro_profissional', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_coordenacao', models.CharField(blank=True, choices=[('Tecnica', 'Técnica'), ('Adjunta', 'Adjunta'), ('Comunidade', 'Comunidade')], max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('pessoa_responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('natureza_servico', models.CharField(blank=True, max_length=255, null=True)),
                ('notas_fiscais', models.FileField(blank=True, null=True, upload_to='notas_fiscais/')),
                ('modalidade_contratacao', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('RPA', 'Recibo de Pagamento Autônomo'), ('CLT', 'Consolidação das Leis do Trabalho'), ('Recibos Simples', 'Recibos Simples')], max_length=50)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('documentos_anexados', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField()),
                ('numero_termo_fomento', models.CharField(blank=True, max_length=100, null=True)),
                ('local_realizacao', models.CharField(max_length=255)),
                ('publico_alvo', models.TextField()),
                ('projeto_escrito', models.FileField(blank=True, null=True, upload_to='projetos/')),
                ('numero_projeto', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Encerrado', 'Encerrado')], default='Em andamento', max_length=50)),
                ('equipe', models.ManyToManyField(through='fillow.EquipeProjeto', to='fillow.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Atendimentos Mensais', 'Atendimentos Mensais'), ('Beneficiários por Psicólogo', 'Beneficiários por Psicólogo'), ('Encaminhamentos', 'Encaminhamentos'), ('Situação Socioeconômica', 'Situação Socioeconômica')], max_length=255)),
                ('conteudo', models.TextField()),
                ('data_geracao', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='fillow.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Lançamento', 'Lançamento'), ('Encerramento', 'Encerramento'), ('Palestra', 'Palestra'), ('Curso', 'Curso'), ('Workshop', 'Workshop')], max_length=100)),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('total_inscritos', models.IntegerField()),
                ('total_presenca', models.IntegerField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='fillow.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='equipeprojeto',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillow.profissional'),
        ),
        migrations.AddField(
            model_name='equipeprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillow.projeto'),
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Psiquiatra', 'Psiquiatra'), ('Fonoaudiólogo', 'Fonoaudiólogo'), ('Neuropsicólogo', 'Neuropsicólogo'), ('Psicopedagogo', 'Psicopedagogo'), ('Terapeuta Ocupacional', 'Terapeuta Ocupacional')], max_length=100)),
                ('data', models.DateField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillow.beneficiario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='fillow.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('data_emissao', models.DateField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillow.beneficiario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoes', to='fillow.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidacaoEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Palestra', 'Palestra'), ('Curso', 'Curso'), ('Workshop', 'Workshop')], max_length=100)),
                ('total_inscritos', models.IntegerField()),
                ('total_presenca', models.IntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidacoes_eventos', to='fillow.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='autorizacoes/')),
                ('data_emissao', models.DateField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillow.beneficiario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='fillow.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presenca', models.BooleanField()),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fillow.beneficiario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='fillow.projeto')),
                ('psicologo', models.ForeignKey(limit_choices_to={'profissao': 'Psicólogo'}, on_delete=django.db.models.deletion.CASCADE, to='fillow.profissional')),
            ],
        ),
    ]
