# Generated by Django 4.2 on 2024-11-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0003_beneficiario_equipeprojeto_profissional_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='fillow.usuario'),
            preserve_default=False,
        ),
    ]
