# Generated by Django 4.2 on 2024-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0004_profissional_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
