# Generated by Django 5.2.9 on 2025-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0005_usuario_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacao',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='autorizacao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='encaminhamento',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='declaracao',
            name='beneficiario',
        ),
        migrations.RemoveField(
            model_name='consolidacaoeventos',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='declaracao',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='encaminhamento',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='equipeprojeto',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='equipeprojeto',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='projeto',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Indivíduo', 'verbose_name_plural': 'Indivíduos'},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='data_criacao',
            new_name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='alcunha',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alcunha/Apelido'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cia Policial'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contem_foto',
            field=models.BooleanField(default=False, verbose_name='Contém Foto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cutis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cútis/Cor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_ultima_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='e_alvo',
            field=models.BooleanField(default=False, verbose_name='É Alvo?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='link_facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nr_infopen',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº INFOPEN'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nr_isp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº ISP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nr_pm',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr PM'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='posto_graduacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posto/Graduação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='prontuario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Prontuário'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saida_temporaria',
            field=models.BooleanField(default=False, verbose_name='Saída Temporária?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='situacao_prisional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação Prisional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status_mandado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status do Mandado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status_situacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação Geral'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='vinculos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vínculos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.DeleteModel(
            name='Atendimento',
        ),
        migrations.DeleteModel(
            name='Autorizacao',
        ),
        migrations.DeleteModel(
            name='Beneficiario',
        ),
        migrations.DeleteModel(
            name='ConsolidacaoEventos',
        ),
        migrations.DeleteModel(
            name='Declaracao',
        ),
        migrations.DeleteModel(
            name='Encaminhamento',
        ),
        migrations.DeleteModel(
            name='EquipeProjeto',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
