# Generated by Django 6.0 on 2025-12-08 14:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fillow', '0006_remove_autorizacao_beneficiario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Plano')),
                ('max_instances', models.PositiveIntegerField(default=1, verbose_name='Limite de Instâncias')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Mensal')),
                ('description', models.TextField(blank=True, verbose_name='Descrição do Plano')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='alcunha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contem_foto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cutis',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='data_ultima_atualizacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='e_alvo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nr_infopen',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nr_isp',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nr_pm',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='posto_graduacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='prontuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='saida_temporaria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='situacao_prisional',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='status_mandado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='status_situacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='vinculos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_groups', related_query_name='usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_user_permissions', related_query_name='usuario', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default=1, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Instância')),
                ('session_id', models.CharField(editable=False, help_text='ID técnico usado na pasta auth do Node.js', max_length=100, unique=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token de Acesso (API)')),
                ('phone_connected', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Criado (Aguardando Start)'), ('QR_SCANNED', 'QR Code Lido'), ('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('BAN', 'Banido pelo WhatsApp')], default='CREATED', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='fillow.plan', verbose_name='Plano Atual'),
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL de Retorno')),
                ('secret', models.CharField(default=secrets.token_hex, editable=False, max_length=64)),
                ('send_messages', models.BooleanField(default=True)),
                ('send_ack', models.BooleanField(default=False)),
                ('send_presence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook', to='fillow.instance')),
            ],
        ),
    ]
