# Generated by Django 6.0 on 2025-12-08 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fillow', '0007_plan_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Aguardando Início'), ('QR_SCANNED', 'QR Code Lido'), ('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('BAN', 'Banido')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_groups', related_query_name='usuario', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_user_permissions', related_query_name='usuario', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='send_ack',
            field=models.BooleanField(default=False, verbose_name='Receber Confirmação de Leitura'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='Receber Mensagens'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='send_presence',
            field=models.BooleanField(default=False, verbose_name='Receber Presença (Digitando...)'),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Retorno'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_jid', models.CharField(max_length=50, verbose_name='Remetente/Destino')),
                ('from_me', models.BooleanField(default=False, verbose_name='Enviado por mim')),
                ('push_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('sticker', 'Figurinha'), ('other', 'Outro')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Conteúdo/Legenda')),
                ('media_url', models.TextField(blank=True, null=True, verbose_name='URL da Mídia (Base64 ou Link)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wamid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID WhatsApp')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fillow.instance')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-timestamp'],
            },
        ),
    ]
