# Generated by Django 6.0 on 2025-12-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0008_instance_profile_pic_url_alter_instance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='agendamento',
            field=models.BooleanField(default=False, verbose_name='Acesso a Agendamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='api',
            field=models.BooleanField(default=False, verbose_name='Acesso à API'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='chatbot',
            field=models.BooleanField(default=False, verbose_name='Acesso ao Chatbot'),
        ),
    ]
