# Generated by Django 6.0 on 2025-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0009_usuario_agendamento_usuario_api_usuario_chatbot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos'), ('lifetime', 'Vitalício')], default='months', max_length=10, verbose_name='Tipo de Duração'),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, help_text="Ex: Se Tipo='Meses' e Tempo=3, o plano dura 3 meses.", verbose_name='Tempo de Duração'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vencimento do Plano'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início do Plano'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='session_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='push_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='remote_jid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='wamid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='send_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='send_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='send_presence',
            field=models.BooleanField(default=False),
        ),
    ]
