# Generated by Django 6.0 on 2025-12-10 18:45

import fillow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0010_alter_message_options_plan_duration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite apenas números ou no formato 000.000.000-00', max_length=14, null=True, unique=True, validators=[fillow.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
