# Generated by Django 6.0 on 2025-12-11 20:50

import django.db.models.deletion
import fillow.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0011_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=fillow.models.user_directory_path, verbose_name='Arquivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('document', 'Documento'), ('sticker', 'Figurinha')], default='document', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Dono do Arquivo')),
            ],
            options={
                'verbose_name': 'Arquivo de Mídia',
                'verbose_name_plural': 'Arquivos de Mídia',
                'ordering': ['-created_at'],
            },
        ),
    ]
