# Generated by Django 6.0 on 2025-12-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0012_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
