# Generated by Django 6.0 on 2025-12-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0013_alter_instance_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_chatbots',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite de Chatbots'),
        ),
    ]
