# Generated by Django 6.0 on 2025-12-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0014_plan_max_chatbots'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_conversations_limit',
            field=models.IntegerField(default=1000, verbose_name='Limite de Conversas/Mês'),
        ),
    ]
