# Generated by Django 6.0 on 2025-12-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0015_plan_monthly_conversations_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='monthly_conversations_limit',
        ),
        migrations.AddField(
            model_name='plan',
            name='conversations_limit',
            field=models.PositiveIntegerField(default=1000, help_text='Quantas conversas o bot pode ter dentro do período selecionado.', verbose_name='Qtd. de Conversas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='conversations_period',
            field=models.CharField(choices=[('daily', 'Diário'), ('monthly', 'Mensal'), ('yearly', 'Anual'), ('lifetime', 'Vitalício (Sem reset)')], default='monthly', help_text='De quanto em quanto tempo o contador de conversas zera.', max_length=20, verbose_name='Período do Limite de Conversas'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos'), ('lifetime', 'Vitalício')], default='months', max_length=10, verbose_name='Vigência (Tipo)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, help_text="Ex: Se Tipo='Meses' e Tempo=3, o plano expira em 3 meses.", verbose_name='Vigência (Tempo)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_chatbots',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite de Criação de Chatbots'),
        ),
    ]
