# Generated by Django 6.0 on 2025-12-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0016_remove_plan_monthly_conversations_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='conversations_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='conversations_period',
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_conversations_limit',
            field=models.IntegerField(default=1000, verbose_name='Limite de Conversas/Mês'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos'), ('lifetime', 'Vitalício')], default='months', max_length=10, verbose_name='Tipo de Duração'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_value',
            field=models.PositiveIntegerField(default=1, help_text="Ex: Se Tipo='Meses' e Tempo=3, o plano dura 3 meses.", verbose_name='Tempo de Duração'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_chatbots',
            field=models.PositiveIntegerField(default=1, verbose_name='Limite de Chatbots'),
        ),
    ]
