# Generated by Django 6.0 on 2026-01-16 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0017_remove_plan_conversations_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('RUNNING', 'Em execução'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Concluída'), ('STOPPED', 'Encerrada')], default='DRAFT', max_length=12)),
                ('strategy', models.CharField(choices=[('ROUND_ROBIN', 'Alternar mensagens (round-robin)'), ('RANDOM', 'Sortear mensagens (random)')], default='ROUND_ROBIN', max_length=12)),
                ('min_delay_seconds', models.PositiveIntegerField(default=20)),
                ('max_delay_seconds', models.PositiveIntegerField(default=45)),
                ('daily_send_limit', models.PositiveIntegerField(default=50)),
                ('require_opt_in', models.BooleanField(default=True)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_campaigns', to='fillow.instance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fillow.broadcastcampaign')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(max_length=20)),
                ('jid', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Falhou'), ('REPLIED', 'Respondeu'), ('OPTED_OUT', 'Opt-out'), ('SKIPPED', 'Ignorado')], default='PENDING', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_wamid', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fillow.broadcastmessage')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='fillow.broadcastcampaign')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastSendLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Falhou')], max_length=10)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('wamid', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fillow.broadcastcampaign')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fillow.broadcastmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fillow.broadcastrecipient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='broadcastcampaign',
            index=models.Index(fields=['owner', 'status'], name='fillow_broa_owner_i_452bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastcampaign',
            index=models.Index(fields=['status', 'next_send_at'], name='fillow_broa_status_1271c9_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['campaign', 'status'], name='fillow_broa_campaig_0203e3_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['jid'], name='fillow_broa_jid_5787a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastrecipient',
            unique_together={('campaign', 'jid')},
        ),
        migrations.AddIndex(
            model_name='broadcastsendlog',
            index=models.Index(fields=['campaign', 'created_at'], name='fillow_broa_campaig_884483_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastsendlog',
            index=models.Index(fields=['recipient', 'created_at'], name='fillow_broa_recipie_a4745e_idx'),
        ),
    ]
