# Generated by Django 6.0 on 2026-01-16 23:07

import django.db.models.deletion
import fillow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0018_broadcastcampaign_broadcastmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ('order', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='broadcastsendlog',
            name='fillow_broa_campaig_884483_idx',
        ),
        migrations.RemoveIndex(
            model_name='broadcastsendlog',
            name='fillow_broa_recipie_a4745e_idx',
        ),
        migrations.AddField(
            model_name='broadcastcampaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='broadcastmessage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='last_send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broadcastsendlog',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='broadcastsendlog',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('QUEUED', 'Em Fila'), ('SENT', 'Enviado'), ('FAILED', 'Falhou'), ('REPLIED', 'Respondeu'), ('OPTED_OUT', 'Opt-out'), ('SKIPPED', 'Ignorado')], default='PENDING', max_length=12),
        ),
        migrations.AlterField(
            model_name='broadcastsendlog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='SENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=fillow.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[fillow.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
