# Generated by Django 6.0 on 2026-01-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0019_alter_broadcastmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastcampaign',
            name='opt_out_keyword',
            field=models.CharField(default='SAIR', max_length=30),
        ),
    ]
