# Generated by Django 6.0 on 2026-01-17 00:49

import django.db.models.deletion
import fillow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0020_broadcastcampaign_opt_out_keyword'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='broadcastcampaign',
            name='fillow_broa_owner_i_452bf7_idx',
        ),
        migrations.RemoveIndex(
            model_name='broadcastcampaign',
            name='fillow_broa_status_1271c9_idx',
        ),
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='broadcastsendlog',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='broadcastsendlog',
            name='message',
        ),
        migrations.AlterUniqueTogether(
            name='broadcastrecipient',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='broadcastrecipient',
            name='fillow_broa_campaig_0203e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='broadcastrecipient',
            name='fillow_broa_jid_5787a6_idx',
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arquivo de Mídia', 'verbose_name_plural': 'Arquivos de Mídia'},
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=fillow.models.user_directory_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='Nome Original'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='Dono do Arquivo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Digite apenas números ou no formato 000.000.000-00', max_length=14, null=True, unique=True, validators=[fillow.models.validate_cpf], verbose_name='CPF'),
        ),
        migrations.RemoveField(
            model_name='broadcastcampaign',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='broadcastcampaign',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='broadcastrecipient',
            name='assigned_message',
        ),
        migrations.RemoveField(
            model_name='broadcastrecipient',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='BroadcastSendLog',
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
        migrations.DeleteModel(
            name='BroadcastCampaign',
        ),
        migrations.DeleteModel(
            name='BroadcastRecipient',
        ),
    ]
