# Generated by Django 6.0 on 2026-02-09 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillow', '0021_remove_broadcastcampaign_fillow_broa_owner_i_452bf7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('min_delay_seconds', models.PositiveIntegerField(default=20)),
                ('max_delay_seconds', models.PositiveIntegerField(default=45)),
                ('messages_per_recipient', models.PositiveIntegerField(default=1)),
                ('use_name_placeholder', models.BooleanField(default=True)),
                ('raw_numbers', models.TextField(blank=True, help_text='Números separados por vírgula/linha (aceita também JID).')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SCHEDULED', 'Agendada'), ('RUNNING', 'Em execução'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada'), ('FAILED', 'Falha')], default='DRAFT', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('total_planned', models.PositiveIntegerField(default=0)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('total_failed', models.PositiveIntegerField(default=0)),
                ('total_delivered', models.PositiveIntegerField(default=0)),
                ('total_read', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_campaigns', to='fillow.instance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_contact_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('jid', models.CharField(db_index=True, max_length=80)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='fillow.dispatchcontactgroup')),
            ],
            options={
                'ordering': ['display_name', 'phone_number'],
            },
        ),
        migrations.CreateModel(
            name='DispatchCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jid', models.CharField(db_index=True, max_length=80)),
                ('phone_number', models.CharField(max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('INLINE', 'Lista avulsa'), ('GROUP', 'Grupo')], default='INLINE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='fillow.dispatchcampaign')),
                ('source_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='fillow.dispatchcontactgroup')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='dispatchcampaign',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='fillow.dispatchcontactgroup'),
        ),
        migrations.CreateModel(
            name='DispatchInstanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_available_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_state', to='fillow.instance')),
                ('last_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_states', to='fillow.dispatchcampaign')),
            ],
            options={
                'verbose_name': 'Estado de Disparo da Instância',
                'verbose_name_plural': 'Estados de Disparo das Instâncias',
            },
        ),
        migrations.CreateModel(
            name='DispatchMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, help_text='Você pode usar {nome} para personalização.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_templates', to='fillow.mediafile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_message_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchCampaignQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField(default=1, help_text='Ordem de envio para este contato (1..N).')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('QUEUED', 'Na fila'), ('SENDING', 'Enviando'), ('SENT', 'Enviado'), ('DELIVERED', 'Entregue'), ('READ', 'Lido'), ('PLAYED', 'Reproduzido'), ('FAILED', 'Falhou'), ('CANCELED', 'Cancelado')], db_index=True, default='QUEUED', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('rendered_body', models.TextField(blank=True)),
                ('wamid', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('node_response', models.JSONField(blank=True, default=dict)),
                ('error_text', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='fillow.dispatchcampaign')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_queue_items', to='fillow.instance')),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='fillow.mediafile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='fillow.dispatchcampaignrecipient')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='fillow.dispatchmessagetemplate')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dispatchcampaign',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='fillow.dispatchmessagetemplate'),
        ),
        migrations.AddConstraint(
            model_name='dispatchcontactgroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_dispatch_group_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='dispatchcontact',
            constraint=models.UniqueConstraint(fields=('group', 'jid'), name='uniq_dispatch_contact_per_group'),
        ),
        migrations.AddConstraint(
            model_name='dispatchcampaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'jid'), name='uniq_dispatch_recipient_per_campaign'),
        ),
        migrations.AddConstraint(
            model_name='dispatchmessagetemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_dispatch_template_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='dispatchcampaignqueueitem',
            index=models.Index(fields=['instance', 'status', 'scheduled_at'], name='fillow_disp_instanc_b3fc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchcampaignqueueitem',
            index=models.Index(fields=['campaign', 'status'], name='fillow_disp_campaig_02c385_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchcampaignqueueitem',
            index=models.Index(fields=['wamid'], name='fillow_disp_wamid_9eb27a_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchcampaignqueueitem',
            constraint=models.UniqueConstraint(fields=('campaign', 'recipient', 'step'), name='uniq_dispatch_queue_step_per_recipient'),
        ),
        migrations.AddIndex(
            model_name='dispatchcampaign',
            index=models.Index(fields=['owner', 'status'], name='fillow_disp_owner_i_0a3a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchcampaign',
            index=models.Index(fields=['instance', 'status'], name='fillow_disp_instanc_3306c8_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchcampaign',
            index=models.Index(fields=['start_at'], name='fillow_disp_start_a_f2013b_idx'),
        ),
    ]
