# Generated by Django 6.0 on 2026-01-07 00:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('analytics', 'Analytics')], max_length=32)),
                ('name', models.CharField(help_text='Nome descritivo da conta de anúncio ou análise.', max_length=255)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Credenciais e tokens de autenticação armazenados como JSON.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta de Anúncio',
                'verbose_name_plural': 'Contas de Anúncio',
                'unique_together': {('user', 'platform', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_text', models.TextField(help_text='Texto base fornecido pelo usuário.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='adsmanager/images/')),
                ('generated_text', models.TextField(blank=True, help_text='Texto gerado pela IA (Gemini)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='adsmanager.adsaccount')),
            ],
            options={
                'verbose_name': 'Criativo',
                'verbose_name_plural': 'Criativos',
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_campaign_id', models.CharField(help_text='ID retornado pela API externa para este campanha.', max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('objective', models.CharField(blank=True, max_length=128, null=True)),
                ('budget_micros', models.BigIntegerField(blank=True, help_text='Orçamento da campanha em micros (1 milhão = 1 unidade de moeda).', null=True)),
                ('status', models.CharField(default='PAUSED', max_length=64)),
                ('economic_mode', models.BooleanField(default=False, help_text='Se verdadeiro, optimizações serão mais conservadoras para orçamentos pequenos.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='adsmanager.adsaccount')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
            },
        ),
        migrations.CreateModel(
            name='AdSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveIntegerField(default=60, help_text='Intervalo entre optimizações em minutos.')),
                ('next_run', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da próxima execução.')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='adsmanager.adcampaign')),
            ],
            options={
                'verbose_name': 'Agendamento de Optimização',
                'verbose_name_plural': 'Agendamentos de Optimização',
            },
        ),
    ]
