# Generated by Django 6.0 on 2026-01-14 20:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gemini', max_length=32)),
                ('model', models.CharField(blank=True, max_length=64, null=True)),
                ('purpose', models.CharField(choices=[('copy', 'Copy/Criação'), ('audit', 'Auditoria'), ('analysis', 'Análise')], default='copy', max_length=16)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('output_chars', models.PositiveIntegerField(default=0)),
                ('tokens_est', models.PositiveIntegerField(default=0)),
                ('cost_est_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uso de IA',
                'verbose_name_plural': 'Uso de IA',
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('min_clicks', models.PositiveIntegerField(default=30)),
                ('min_conversions', models.PositiveIntegerField(default=1)),
                ('max_cpa_micros', models.BigIntegerField(blank=True, null=True)),
                ('min_roas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('scale_up_pct', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('scale_down_pct', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_scale_up_pct_per_day', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('cooldown_hours', models.PositiveIntegerField(default=12)),
                ('hard_pause_on_zero_conversions_days', models.PositiveIntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Otimização',
                'verbose_name_plural': 'Regras de Otimização',
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('sync', 'Sincronizar'), ('optimize', 'Otimizar'), ('create', 'Criar'), ('duplicate', 'Duplicar')], max_length=16)),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='success', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
            },
        ),
        migrations.CreateModel(
            name='CampaignMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads')], max_length=32)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('cost_micros', models.BigIntegerField(default=0)),
                ('conversions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('conversion_value_micros', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica Diária',
                'verbose_name_plural': 'Métricas Diárias',
            },
        ),
        migrations.CreateModel(
            name='UserAdsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_enabled', models.BooleanField(default=True)),
                ('ai_provider', models.CharField(choices=[('gemini', 'Gemini')], default='gemini', max_length=32)),
                ('ai_model', models.CharField(default='gemini-2.5-flash', max_length=64)),
                ('ai_daily_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ai_monthly_limit_usd', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('global_daily_spend_cap_micros', models.BigIntegerField(blank=True, null=True)),
                ('global_monthly_spend_cap_micros', models.BigIntegerField(blank=True, null=True)),
                ('allow_auto_sync', models.BooleanField(default=True)),
                ('allow_auto_optimize', models.BooleanField(default=True)),
                ('allow_auto_pause', models.BooleanField(default=True)),
                ('allow_auto_duplicate', models.BooleanField(default=False)),
                ('allow_auto_refresh_creatives', models.BooleanField(default=False)),
                ('default_economic_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Usuário (Ads)',
                'verbose_name_plural': 'Configurações do Usuário (Ads)',
            },
        ),
        migrations.AlterModelOptions(
            name='adschedule',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='budget_type',
            field=models.CharField(choices=[('daily', 'Diário'), ('lifetime', 'Vitalício'), ('unknown', 'Indefinido')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='platform_adset_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='platform_budget_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='spend_cap_daily_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='spend_cap_monthly_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='destination_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='google_asset_resource_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adcreative',
            name='meta_creative_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='adsaccount',
            name='currency_code',
            field=models.CharField(default='BRL', max_length=8),
        ),
        migrations.AddField(
            model_name='adsaccount',
            name='currency_minor_unit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='adsaccount',
            name='platform_account_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='adsaccount',
            name='spend_cap_daily_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adsaccount',
            name='spend_cap_monthly_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adschedule',
            name='kind',
            field=models.CharField(choices=[('sync', 'Sincronizar'), ('optimize', 'Otimizar')], default='optimize', max_length=16),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='budget_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='economic_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='platform_campaign_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='base_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adcreative',
            name='generated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adsaccount',
            name='credentials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='adsaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adsaccount',
            name='platform',
            field=models.CharField(choices=[('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('analytics', 'Analytics (GA4)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='adschedule',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='adschedule',
            name='next_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['account', 'platform_campaign_id'], name='adsmanager__account_10080d_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status'], name='adsmanager__status_11c7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='adschedule',
            index=models.Index(fields=['active', 'next_run'], name='adsmanager__active_d3470e_idx'),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='adsmanager.adcampaign'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='adsmanager.adcampaign'),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmetricsnapshot',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='adsmanager.adcampaign'),
        ),
        migrations.AddField(
            model_name='useradssettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ads_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiusagelog',
            index=models.Index(fields=['user', 'created_at'], name='adsmanager__user_id_461888_idx'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['run_type', 'status', 'started_at'], name='adsmanager__run_typ_fa04ea_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmetricsnapshot',
            index=models.Index(fields=['campaign', 'date'], name='adsmanager__campaig_a0968e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignmetricsnapshot',
            index=models.Index(fields=['date'], name='adsmanager__date_41a2fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmetricsnapshot',
            unique_together={('campaign', 'date', 'source')},
        ),
    ]
